name: sync
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync main
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wangworld/ac_nodejs.git"
          source_branch: "main"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
      
      - name: sync gitee
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/wangworld/ac_nodejs.git"
          source_branch: "gitee"
          destination_branch: "gitee"
          github_token: ${{ secrets.PAT }}
